### ISSUE TITLE
Tensor save/load issues

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#123]
The testing work here https://github.com/xamarin/TorchSharp/issues/143 has raised some issues. For each we should compare to PyTorch

1. Should save/load on a GPU tensor bring it back as a GPU tensor?

2. Should the serialization format record the device, dtype and backend?  It currently does

3. Should the serialization format for TorchRawTensor be precisely the format used by Torch?  Currently DiffSharp uses .NET binary serialization.  We could use the save/load routines from Torch for tensors (see https://github.com/xamarin/TorchSharp/pull/148)

**Comment by dsyme** [comment]
`tensor.Save` and `TorchTensor.Load` are now available in the TorchSharp version we are using.

**Comment by dsyme** [comment]
Current behaviour is a GPU tensor will come back as a GPU tensor

**Comment by VisualMelon** [comment]
While looking at #173 (fix in https://github.com/VisualMelon/DiffSharp/tree/Issue173, which I think is fine for the time being), a couple of things jumped out at me:
 - Tensors are not moved to the default device on load (they are moved to whatever device it says in the serialisation file). That won't change the test behaviour, but it could make sense, since presumably that's the device you intend to use. This would essentially mean not storing/ignoring the device information in the tensor. I don't know if there are use cases for actually storing the device, but such a requirement would suggest a way to configure realisation directly.
 - It also looks like load won't work if only the reference backend is available, because they are created on the Torch backend, but I should actually test that to check if it matters. Again (and ignoring the current implementation), would it make sense for them to be loaded onto the default backend?

**Comment by dsyme** [comment]
> It also looks like load won't work if only the reference backend is available, because they are created on the Torch backend, but I should actually test that to check if it matters. Again (and ignoring the current implementation), would it make sense for them to be loaded onto the default backend?

Yes, I discussed this with @gbaydin and the plan is to change so that the backend and device are not saved in the tensor serialization, and instead tensor.load takes the requested backend and device (or else defaults to the default)

**Comment by dsyme** [comment]
@VisualMelon Actually for #173 the change here was inadvertent https://github.com/DiffSharp/DiffSharp/pull/172/files#diff-dca951cab2ee0dc4d6b2ad884ac2e1d8R812

I'll revert that and that should fix the GPU test failur (though doesn't fix this issue)

**Comment by dsyme** [comment]
@VisualMelon If you'd like to make and test the fix, the lines
```
            info.AddValue("device", tCpu.Device)
            info.AddValue("dtype", tCpu.Dtype)
            info.AddValue("shape", tCpu.Shape)
```
should be
```
            info.AddValue("device", t.Device)
            info.AddValue("dtype", t.Dtype)
            info.AddValue("shape", t.Shape)
```
This restores the code to the status quo of saving the original tensor's device

**Comment by VisualMelon** [comment]
@dsyme All tests are passing with that change (https://github.com/VisualMelon/DiffSharp/tree/Issue123) on CPU and GPU.

**Comment by dsyme** [comment]
COol, I'll submit that change here https://github.com/DiffSharp/DiffSharp/pull/178

**Comment by dsyme** [comment]
#186 resolved most of this

* Should save/load on a GPU tensor bring it back as a GPU tensor? 

  Resolution: No the tensors are brought back on the specified or default backend configuration

* Should the serialization format record the device, dtype and backend? 

  Resolution: The dtype is stored, and the backend used to save must be available on reload (though the tensor is moved to the specified or default backend)

* Should the serialization format for TorchRawTensor be precisely the format used by Torch? 

  Resolution: No currently DiffSharp uses .NET binary serialization. We could separately make available the save/load routines from Torch for tensors (see xamarin/TorchSharp#148)

**Comment by gbaydin** [comment]
@dsyme thank you for documenting the decisions and resolutions.

> Should save/load on a GPU tensor bring it back as a GPU tensor?
> Resolution: No the tensors are brought back on the specified or default backend configuration

Note that this is different from the PyTorch convention, where a GPU tensor when serialized and deserialized, comes back to the same GPU device and the deserialization simply fails if the device is no longer there, you're on a different machine etc. 

There are some use cases for this default behavior, mostly to do with neural network training on multiple GPUs. PyTorch allows an optional argument for deserialization that can override the target device so that you can revive the tensor on a different device than the one it was saved with.

However, this behavior of PyTorch has been somewhat annoying for me and (other people I'm working with), so I think the resolution we have here is good.

> Should the serialization format record the device, dtype and backend?
> Resolution: The dtype is stored, and the backend used to save must be available on reload (though the tensor is moved to the specified or default backend)
Cool.

> Should the serialization format for TorchRawTensor be precisely the format used by Torch?
> Resolution: No currently DiffSharp uses .NET binary serialization. We could separately make available the save/load routines from Torch for tensors (see xamarin/TorchSharp#148)

I like this current resolution, keeping in mind we can change it in the future. I think having the same serialization format as the common denominator across multiple backends is a nice design. We also do a bit of gzip compression in the dotnet binary serialization process, which I think is useful. I think any changes about the serialization format should be guided by performance and compatibility experiments.
