### ISSUE TITLE
Discussion: Matrix/Vector/Scalar programming with API  

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#139]
There's no rush with this, I just want to open the issue while it's on my mind.

In #138 I did a trial port of the DiffSharp 0.7 samples from the DiffSharp 0.7 documentation.  

Unsurprisingly I noticed that the shift to tensors has an impact on the programming.  I found myself definitely wanting some helper definitions to stay in the "matrix/vector/scalar" sweet spot of DiffSharp 0.7. So I ended up writing helpers for myself like these. 
```fsharp
open DiffSharp

type Scalar = Tensor
type Vec = Tensor
type Mat = Tensor
[<AutoOpen>]
module Globals =
    let v (x: 'T) : Scalar = dsharp.tensor x
    let vec (x: 'T seq) : Vec = dsharp.tensor x
    let mat (x: seq< #seq<'T> >) : Mat = dsharp.tensor x
    let value (x: Tensor) : 'T = x.toScalar() :?> 'T
    let values (x: Tensor) : 'T = x.toArray() :?> 'T

module Vec =
    let zeros n : Vec = dsharp.zeros [n]
    let full n x : Vec = dsharp.full([n],x)
    let init n f : Vec = dsharp.full([n],[| for i in 0 ..n-1 -> f i|])
    let length (v: Vec) = v.shape.[0]
    let min (v: Vec) = v.min()
    let max (v: Vec) = v.max()
    let sum (v: Vec) = v.sum()
module Mat =
    let zeros n m : Mat = dsharp.zeros [n; m]
    let full n m x : Mat = dsharp.full([n;m],x)
    let init n m f : Mat = dsharp.full([n;m],[| for i in 0 ..n-1 do for j in 0..m-1 do yield f i j|])
    let initRows n (f: int -> Vec) : Mat = dsharp.tensor([| for i in 0 ..n-1 do yield f n |])
    let initCols n (f: int -> Vec) : Mat = dsharp.tensor([| for i in 0 ..n-1 do yield f n |]).transpose()
    let nrows (v: Mat) = v.shape.[0]
    let ncols (v: Mat) = v.shape.[1]
```

Note I adpted the name changes
* type/module D --> Scalar
* type/module DV --> Vec
* type/module DM --> Mat
* `D 3.0` --> `v 3.0` (`v` for Value, could be `s`)
* `toDV [1;2;3]` --> `vec [1,2,3,]`
* `toDM ...` --> `mat [ [ 1,2], [3,4] ]`

There is of course no static enforcement of these distinctions (Scalar, Vec and Mat are all just abbreviations for Tensor)

I really just want to mention that I found myself doing this rather than just erasing to Tensor everywhere (even if Scalar, Vec and Mat are all just abbreviations for Tensor). I think we'll find that other users will do the same thing.  Is there any corresponding naming system for this with pytorch or numpy?

**Comment by gbaydin** [comment]
> Is there any corresponding naming system for this with pytorch or numpy?

No, not that I know of. Users are expected to embrace the notion of ndarrays and tensors, without any special casing for scalars, vectors, matrices. I also fully support that style because it's much simpler to work with and think about one type of object with different dimensions. Also mentally it generalizes very well to add extra dimensions that represent image channels, minibatch items, sequence dimensions, lots of other things.

I'm not sure if this is a good idea, but: perhaps there is a way of introducing some optional strong type wrapping a Tensor that also has the dimensionality as a part of the type, like `D0` for scalar, `D1` for vector, etc. up to some `Dn` where `n` can be 9. Nine dimensions should be enough---sounds like a sentence that can be ridiculed in the future like "640kB should be enough" :)

About the DiffSharp 0.7 samples, my intention is to completely rewrite them with the modern tensor workflow in mind, rather than porting the existing code.

**Comment by dsyme** [comment]
> I'm not sure if this is a good idea, but: perhaps there is a way of introducing some optional strong type wrapping a Tensor that also has the dimensionality as a part of the type, like D0 for scalar, D1 for vector, etc. up to some Dn where n can be 9. (Perhaps T0...Tn is a better name.) Nine dimensions should be enough---sounds like a sentence that can be funny in the future like "640kB should be enough" :)

I think there are three stable points for additional checking in F#

1. extra shape checking and inference tooling per #130 

2. a set of dimensioned types D0.. D6 (with aliases for Scalar, Vec, Mat...) plus (really quite large) API duplication across all of these.  After D6 I think it becomes hard and at some point you'd just force people to use tensors.  

3. attempts to do the same with type providers to generate the space programatically

There are pros and cons across each.  

I guess I'd like to see 

* (1) in the core DiffSHarp tooling, per #130, regularly used and always being improved

* (2) as an optional additive library built on top of DiffSharp

The advantage of (1) is it deals (approximately) with both dimensionality and dimension sizes.  The challenge is lining everything up to get it integrated into F# tooling and F# notebooks

**Comment by dsyme** [comment]
Closing this for now - maybe a topic for docs
