### ISSUE TITLE
kmeans examples of diffsharp

### ISSUE THREAD

**Issue by summersunshine1** [DiffSharp/DiffSharp#45]
kmeans is an unsupervised algrorithmn,but the example used on sgd used label of data which is y in function below,can this represent the sgd is suitable for kmeans?
let sgd f w0 (eta:D) epsilon (t:(DV*DV)[]) =
    let rec desc w =
        let x, y = t.[rnd.Next(t.Length)]
        let g = grad (fun wi -> DV.l2norm (y - (f wi x))) w
        if DV.l2norm g < epsilon then w else desc (w - eta * g)
    desc w0
sorry i am very curious about this,could anyone explain this?thank you.
The example i saw was on http://diffsharp.github.io/DiffSharp/
@gbaydin

**Comment by barak** [comment]
Yeah, the code doesn't seem to quite match the text. Thanks for pointing out the issue. We'll have to make an edit pass.

**Comment by gbaydin** [comment]
Hi @summersunshine1, there is no supervised training or a data labels in `y` in that example.

The way k-means clusters are assigned with SGD is just a simple hack to use the same, previously introduced, SGD code that you quoted in your message. The value `0` is used as a fake "label" so that the distance of each data point to its current nearest mean is decreased towards zero.

This is very briefly mentioned in [the text](http://diffsharp.github.io/DiffSharp/examples-kmeansclustering.html), here:
![screenshot_2017-11-24_11-36-09](https://user-images.githubusercontent.com/5365982/33209021-eb2114d2-d10b-11e7-93e0-f97364c199f6.png)

This is where the all-zero fake "labels" are created in the code:
```fsharp
let wopt = Array.zip data (Array.create data.Length (toDV [0.])) |> sgd dist w0 (D eta) (D epsilon)
```

You're right that it's a bit confusing to formulate it this way. In general all of DiffSharp examples on the website need a significant edit pass.

**Comment by summersunshine1** [comment]
Hi,I reread your code ,i think it is suitable for kmeans with sgd but it isn't a  classical kmeans method which firstly assign samples to different centers and then  update centers with these samples

**Comment by gbaydin** [comment]
Yes, it is indeed a different formulation of the k-means problem as a differentiable objective which you can optimize using gradient descent. The motivation for this was to show what can be achieved with automatic differentiation techniques, the main focus of DiffSharp.

**Comment by dsyme** [comment]
Closing because this is out of date for DiffSHarp 1.0. We may revist
