### ISSUE TITLE
Test issue: Assert.AreEqual

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#79]
Just to mention that in all our calls `Assert.AreEqual(t0, t0Correct)` these are the wrong way around - the expected should come first for `Assert.AreEqual` 

This affects the error messages when tests fail.

In any case I'd like to change this to a helper `assertEqual: T * T -> unit` that enforces that the types of the two things are the same. The `Assert.AreEqual(obj,obj)` overload can hide obscure errors.

**Comment by gbaydin** [comment]
Thank you, I reordered all `Assert.AreEqual` calls so that the expected value goes first. 

About the `assertEqual: T * T -> unit`: I understand it would enforce F# type checking before calling `Assert.AreEqual`, but I think non-matching types would already trigger test errors with `Assert.AreEqual`. In other words I find it difficult to imagine a case where `Assert.AreEqual` would be satisfied when types are different.

**Comment by dsyme** [comment]
Great thanks. 

I think there are lots of cases, eg two sequences are considered equal, even if one is a list and another an array.
